update 3 files for my task No.5
Thesharing/douban-spider pull request #2
Opened 2019-11-25 11:02 UTC by secrettttt

2019-12-02 14:32 UTC, Thesharing requested changes
Need a lot of changes.

2019-12-02 14:32 UTC, Thesharing commented on doubanspider/spider.py
用requests就可以访问了，不需要用selenium，seleniums本身的资源开销太大了
requests直接用类里封装好的`self.session`即可
注意改headers

2019-12-02 14:32 UTC, Thesharing commented on doubanspider/test_spider.py
> +        # cls.content, cls.selector = cls.spider.access_brief('https://movie.douban.com/subject/26786669/')
这行为什么要注释掉……

2019-12-02 14:32 UTC, Thesharing commented on main.py
> +
main函数不需要推上来

2019-12-08 04:30 UTC, secrettttt commented
应该可以了(⊙o⊙)…

2019-12-13 14:16 UTC, Thesharing requested changes
👍 已经差不多快完成了~ 只需要把print去掉，返回的部分修改一下即可

然后将commit合并起来，查询`git rebase 合并 commit`就行

2019-12-13 14:16 UTC, Thesharing commented on doubanspider/spider.py
> +    def access_comment_one_page(self, movie_id, start, sort="new_score", status="P"):
这个实际上写成access_comment的nested function就好

2019-12-13 14:16 UTC, Thesharing commented on doubanspider/spider.py
> +            print(soup)
print不应该推上来的😂

2019-12-13 14:16 UTC, Thesharing commented on doubanspider/spider.py
> +            print("访问第" + str(int(start / 20)) + "页，返回的数据：")
这里也是~

2019-12-13 14:16 UTC, Thesharing commented on doubanspider/spider.py
> +        url = str("https://movie.douban.com/subject/" + str(movie_id) + "/comments?start=" +
这里最好用
```python
url = 'https://movie.douban.com/subject/{}/comments'.format(movie_id)
params = {
    'start': start, 
    'limit': '20',
...
}
html = self._get(url, params=params, headers=HEADERS['comment'])
```
这样方便修改网址的参数

2019-12-13 14:16 UTC, Thesharing commented on doubanspider/spider.py
> +            res.append(self.access_comment_one_page(movie_id, start, sort, status))
这里最好能用生成器`yield`的方式返回而非用整个list返回 否则要爬完整个列表才能开始抓第一个短评

2019-12-14 05:37 UTC, secrettttt commented
好了~~~

2019-12-15 18:33 UTC, Thesharing requested changes
👍 还有一些小细节需要完善

2019-12-15 18:33 UTC, Thesharing commented on doubanspider/spider.py
> +        return 'done'
这里不需要返回'done' 对于生成器来说这里直接结束就可以了

2019-12-15 18:33 UTC, Thesharing commented on doubanspider/spider.py
> +        url = str("https://movie.douban.com/subject/" + str(movie_id) + "/comments?start=" +
`url` 这里最好用：

```python3
url = 'https://movie.douban.com/subject/{}/comments'.format(movie_id)
params = {
    'start': start, 
    'limit': '20',
...
}
html = self._get(url, params=params, headers=HEADERS['comment'])
```

这样方便修改网址的参数

2019-12-19 14:35 UTC, secrettttt commented
(๑‾ ꇴ ‾๑)好哒

2019-12-21 09:14 UTC, Thesharing commented
Merged.

2019-12-21 09:14 UTC, closed without merging