crawl celebrities message
Thesharing/douban-spider pull request #3
Opened 2019-11-26 03:58 UTC by zcsure

crawl celebrities message

2019-12-02 17:52 UTC, Thesharing requested changes
Good job, still get some changes to make.

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/extract/celebrity.py
> +    """
1. python函数名、参数列表和变量名都不用驼峰，改用下划线连接
2. class内部使用的类方法前面加一个下划线
3. 这个函数名表明不了函数的意思

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/extract/celebrity.py
> +    title = position.split(" ")[1] #获取职位
这里如果中间可能会出现多个空格的话得用`re.split(r'\s+)`，如果不包含多个空格直接用`str.split()`就行

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/extract/celebrity.py
> +        director['works'] = workList
这里用List Comprehension就行
```python
director['works'] = [work.text for work in works[0].find_all('a')] if works else None
```

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/extract/celebrity.py
> +        staffList[title] = directorList
这块没必要在前面声明一个list 然后append 最后在放在这里……
直接`staff_list[title] = [director]`就好

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/headers.py
> +        'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36',
这里不应该改 回来我会改成config的形式

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/headers.py
> +    'proxies':{
这个proxy是因为遇到反爬了吗……

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/util.py
> +def save_to_mongodb(result,mongodb_db,mongodb_table,mongodb_url = 'mongodb://localhost:27017/'):
mongo这部分可以不推上来 之后我会统一写一个database的部分

2019-12-02 17:52 UTC, Thesharing commented on requirements.txt
> +pymongo
同样 requirements这块也没必要改 spiderutil里面已经有pymongo的依赖了

2019-12-02 17:52 UTC, Thesharing commented on doubanspider/test_spider.py
> +        print(celebrities)
unit test里面不需要print出来信息
相反 这里应该通过`assertEqual(len(celebrities), N)`来判断是否得到正确结果
甚至还需要通过celebrities里面的属性来判断

2019-12-03 15:47 UTC, zcsure commented on doubanspider/headers.py
> +        'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36',
这可能是mac系统的原因？我没记得有改过这个

2019-12-03 15:48 UTC, zcsure commented on doubanspider/headers.py
> +    'proxies':{
嗯，不过加了也没用，ip已经被封了。

2019-12-03 15:50 UTC, zcsure commented on doubanspider/test_spider.py
> +        print(celebrities)
不同电影的演职人员种类不一样，没想到什么好的方法来验证正确结果

2019-12-03 17:04 UTC, Thesharing requested changes
Good job 👍

2019-12-03 17:04 UTC, Thesharing commented on doubanspider/test_extract.py
> +        staff_list = extract_celebrities(self.celebrities)
这里用一个示例就可以~ 在这个case通过session.get获取一个页面解析判断得到的数量即可

2019-12-03 17:04 UTC, Thesharing commented on requirements.txt
> +requests
requests也不需要加 spiderutil里面都涵括了

2019-12-03 17:04 UTC, Thesharing commented on doubanspider/extract/celebrity.py
> +    """
建议改成`_collect_staff_list`

2019-12-05 15:50 UTC, zcsure commented
Task 4: Celebrity List

2019-12-13 14:00 UTC, Thesharing requested changes
👍 基本上快完成了~ 不过在提交代码前把代码格式化一下~

然后将多个commit 合并成一个commit，具体可以参考`git rebase 合并 commit`

2019-12-13 14:00 UTC, Thesharing commented on doubanspider/extract/celebrity.py
> +    staff_list[title] = one_staff_list
这块可以直接把`one_staff_list`作为返回值，这样`staff_list`和`title`是没必要传进来的

2019-12-13 14:00 UTC, Thesharing commented on doubanspider/spider.py
> +            start += 1  #start应该递增
这块确实我写错了😂 不过应该是`start += 20`

2019-12-13 14:00 UTC, Thesharing commented on doubanspider/test_extract.py
> +        cls.celebrities = cls.spider.access_celebrity('26786669')
这里没有必要把celebrities放到类变量里，因为只有`test_extract_celebrity`一个测试类会调用这个

直接写成：

```python
celebrities = cls.spider.access_celebrity('26786669')
staff_list = extract_celebrities(celebrities)
self.assertTrue(staff_list['Director'])
```

2019-12-13 14:00 UTC, Thesharing commented on doubanspider/util.py
> +# 工具类
这个地方好像没有修改……感觉好像是去掉了一个回车 可以把这里的修改去掉

2019-12-21 08:59 UTC, Thesharing commented
Merged.

2019-12-21 09:00 UTC, closed without merging