comments part
Thesharing/douban-spider pull request #5
Opened 2019-11-27 13:45 UTC by toutengxian

2019-12-02 18:24 UTC, Thesharing requested changes
Excellent job! Resubmit without changes in `access_comment`.

2019-12-02 18:24 UTC, Thesharing commented on doubanspider/spider.py
> +        url = 'https://movie.douban.com/subject/' + str(movie_id) + '/comments?start=' + str(
这里实际上参数应该以params的方式传入，具体搜`requests params`就好 
不过这个函数本身也应该是Task 5提交的 这里其实不应该提交这部分改动的

2019-12-02 18:24 UTC, Thesharing commented on doubanspider/spider.py
> +        url = 'https://movie.douban.com/subject/' + str(movie_id) + '/comments?start=' + str(
这一部分可以放到Unit test的`test_extract_comments`里面

2019-12-13 14:21 UTC, Thesharing requested changes
👍 已经基本快完成了，只需要修改返回方式，以及和 #2 对接一下即可。

另外需要将commit合并一下，参考`git rebase 合并 commit`

2019-12-13 14:21 UTC, Thesharing commented on doubanspider/extract/comment.py
> +        results.append({
这块采用生成器的方法将结果`yield`即可

2019-12-13 14:21 UTC, Thesharing commented on doubanspider/test_extract.py
> +        cls.comments = cls.spider.access_comment(26786669)
这里的access_comment好像是没有用的……？

2019-12-13 14:21 UTC, Thesharing commented on doubanspider/extract/comment.py
> +    soup = Soup(text)
这里可能需要看一下 #2 那边的实现，他那边传的应该是已经是一个页面的Soup了 可以跟他协商一下接口

2019-12-13 14:21 UTC, Thesharing commented on doubanspider/test_extract.py
> +        results = extract_comments(text)
同样，如果 #2 那边导致`extract_comment`接口变了，这边可能需要相应地修改。

2019-12-14 16:57 UTC, toutengxian commented
都改好啦

2019-12-17 10:25 UTC, toutengxian commented
学长好 已经都改好啦 但是合并commit的时候遇到了点问题 vim修改好之后它显示还有conflict没有解决 暂时不知道该怎么处理

2019-12-23 07:30 UTC, Thesharing commented
Merged

2019-12-23 07:30 UTC, closed without merging